version: "3.9"
services:
  hbbs:
    build: ./
    pull_policy: build
    image: hbbs:latest
    container_name: hbbs
    ports:
      - 3000:3000
    restart: always
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
  nginx:
    build: ./nginx
    pull_policy: build
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always